#!/usr/bin/env Rscript

#suppressWarnings(suppressMessages(library(tickdb)))

printf=function(...) invisible(cat(sprintf(...)))

if(!interactive())
{
	args = commandArgs(trailingOnly=T)
	if(length(args)!=12)
	{
		printf("Usage: sample <measurement> <product> <type> <from> <to> <start> <end> <frequency> <front> <rolldays> <config> <output>\n")
		printf("\n\033[4mParameters\033[24m:\n\n")
		printf("\033[1mmeasurument\033[22m\tbook or trade\n")
		printf("\033[1mproduct\033[22m\t\tproduct name. For example: FESX\n")
		printf("\033[1mtype\033[22m\t\tproduct type. For example F for futures, O for options\n")
		printf("\033[1mfrom\033[22m\t\tStart date as YYYYMMDD\n")
		printf("\033[1mto\033[22m\t\tEnd date as YYYYMMDD\n")
		printf("\033[1mstart\033[22m\t\tstart time as HH\n")
		printf("\033[1mend\033[22m\t\tend time as HH\n")
		printf("\033[1mfrequency\033[22m\tfrequency of sample. Examples: 10m for 10 minutes, 3h for 3 hours\n")
		printf("\033[1mfront\033[22m\t\t1 for front month, 2 for first back month, 3 for second back month, etc...\n")
		printf("\033[1mrolldays\033[22m\tnumber of days to roll the contract before expiry date\n")
		printf("\033[1mconfig\033[22m\t\tjson config file to access the Influx database\n")
		printf("\033[1moutput\033[22m\t\tname of the csv output file\n")
		printf("\n")
		quit(status=1)
	}


	x = sample_price(args[1],args[2],args[3],as.integer(args[4]),as.integer(args[5]),
					 period(as.integer(args[6]),as.integer(args[7])),
					 args[8], # frequency
					 as.integer(args[9]),as.integer(args[10]),
					 args[11] # config
					 )
	z = do.call(rbind,x)
	write.csv(z,args[12])
}
